/* Presentation only; uses the existing Markets persistence and action handlers. */
(() => {
  const e=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const url=value=>{try{const u=new URL(value);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'#'}catch{return '#'}};
  const stamp=value=>value&&Number.isFinite(Date.parse(value))?new Intl.DateTimeFormat('zh-CN',{timeZone:'Asia/Shanghai',month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit',year:'numeric',hourCycle:'h23'}).format(new Date(value)):'时间未提供';
  const pct=n=>Number.isFinite(n)?`${n>0?'+':''}${n.toFixed(2)}%`:'—';
  const names={rates:'央行与利率',economy:'通胀与经济',energy:'能源与商品',world:'国际与贸易',china:'中国与香港',company:'行业与公司'};
  const link=(href,label,cls='')=>`<a class="${cls}" href="${e(url(href))}" target="_blank" rel="noopener noreferrer">${e(label)} ↗</a>`;
  const button=(action,label,id,extra='')=>`<button type="button" class="btn ghost" data-mk="${action}" ${id?`data-id="${e(id)}"`:''} ${extra}>${label}</button>`;
  function relevant(n,state){const sectors=JING_MARKET_CATALOG.filter(s=>state.sectors.includes(s.id)&&n.sectors?.includes(s.id));return sectors.length?sectors.map(s=>s.name).join('、')+'：主题相关，实际影响需结合原文核实。':({rates:'关注政策是否已落地，以及与此前表述的变化。',economy:'留意公布值与统计期；未接入一致预期，不判断是否超预期。',energy:'观察供需、库存与运输变化，不把新闻直接等同油价走势。',world:'观察是否涉及贸易、运输或供应链；不预设市场方向。',china:'观察货币、金融监管和区域经济变化。',company:'公司自己的公告，应结合财务披露与其他来源核实。'}[n.category]||'先核实原始信息，再判断与你的关联。');}
  function article(n,state,busy){const a=state.analysis[n.id],related=n.related||[];return `<article class="mk-article" data-article="${e(n.id)}"><div class="mk-byline"><span class="mk-tag ${n.kind==='官方'?'official':''}">${e(n.status||JING_MARKET_RULES.classify(n))}</span><span>${e(names[n.category]||'综合')}</span><span>${e(stamp(n.publishedAt))} · 北京时间</span>${n.sourceStale?'<span class="mk-amber">缓存来源</span>':''}</div><h4>${link(n.url,n.title)}</h4><p class="mk-excerpt">${e(n.snippet||'订阅源未提供摘要，请查看原文。')}</p><div class="mk-byline">${e(n.source)}${related.length?` · 已合并 ${related.length+1} 条相似报道`:''}</div><div class="mk-actions">${button('save',state.saved[n.id]?'已收藏':'收藏',n.id)}${button('note',state.notes[n.id]?'编辑笔记':'写笔记',n.id)}${button('explain',busy===n.id?'正在解读…':a?'重新解读':'中文解读',n.id,busy?'disabled':'')}</div>${state.notes[n.id]?`<p class="mk-personal">我的观察：${e(state.notes[n.id])}</p>`:''}<details class="mk-detail" ${a?'open':''}><summary>${a?'查看中文解读与来源':'展开关联与来源'}</summary><p><b>与你的关联：</b>${e(relevant(n,state))}</p><p class="mk-muted">报道时间：${e(stamp(n.publishedAt))}。事件发生时间：订阅源未单独提供，不等同报道时间。</p>${related.length?related.map(r=>`<p>${link(r.url,r.source+' · '+r.title)}</p>`).join(''):''}${a?`<div class="mk-explanation"><b>AI 解读 · 不是新闻原文</b><p><b>事实摘要：</b>${e(a.summary)}</p><p><b>可能影响：</b>${e(a.impact)}</p><p><b>接下来留意：</b>${e(a.watch)}</p><div class="mk-muted">${e(a.basedOn)} · ${e(stamp(a.generatedAt))}</div>${button('deleteAI','删除解读',n.id)}</div>`:'<p class="mk-muted">中文解读需你同意后调用现有 AI 服务；当前显示的是订阅源内容和规则关联。</p>'}</details></article>`;}
  function highlights(state){const items=JING_MARKET_RULES.prioritize(state.snapshot?.news||[],state.sectors);return `<section class="mk-highlights"><div class="mk-section-heading"><div><span class="mk-eyebrow">THE DAILY BRIEF</span><h3>今日重点 <span>最多三件，值得先看</span></h3></div><details class="mk-ranking"><summary>如何选出？</summary><p>在过去 24 小时的可核实发布时间内，按关注关联、官方来源、政策／数据／经营变化及新鲜度排序。排除过期缓存，合并高度相似且数值一致的标题。仅为可解释的规则筛选，不是投资评级，不依据“暴跌”等情绪词加分。</p></details></div><div class="mk-highlight-grid">${items.map((n,i)=>`<article class="mk-highlight"><div class="mk-highlight-top"><span class="mk-rank">0${i+1}</span><span class="mk-tag">${e(n.status)}</span><span class="mk-muted">${e(names[n.category])}</span></div><h4>${link(n.url,n.title)}</h4><p class="mk-clamp">${e(state.analysis[n.id]?.summary||n.snippet||'请查看原文，订阅源未提供摘要。')}</p>${state.analysis[n.id]?'<span class="mk-muted">上文为 AI 摘要，需核实原文</span>':''}<div class="mk-relevance"><b>与你的关联</b><span>${e(relevant(n,state))}</span></div><div class="mk-highlight-foot"><span>${e(n.source)} · ${e(stamp(n.publishedAt))}</span>${button('focusArticle','展开',n.id)}</div></article>`).join('')||'<div class="mk-empty mk-highlight-empty"><b>今天暂未筛出足够可靠的重点。</b><p>不拿旧消息填充首页。你仍可浏览下方消息，或检查来源连接状态。</p></div>'}</div></section>`;}
  function timeline(state){const s=state.snapshot,list=s?.events||[],sources=s?.calendarSources||[];return `<aside class="mk-panel mk-timeline"><div class="mk-section-heading"><div><span class="mk-eyebrow">LOOKING AHEAD</span><h3>未来七天</h3></div><span class="mk-tag">北京时间</span></div><p class="mk-muted">先知道何时公布，再看实际结果。</p><div class="mk-events">${list.map(ev=>`<article class="mk-event"><div class="mk-event-time">${ev.dateOnly?e(ev.date)+' · 仅日期':e(stamp(ev.at))}</div><h4>${link(ev.url,ev.title)}</h4><span class="mk-tag">${e(ev.status)}</span>${ev.sourceStale?'<span class="mk-amber">缓存日程 · 请核实</span>':''}<p>${e(ev.timeNote)}</p><span class="mk-muted">${e(ev.source)}</span></article>`).join('')||'<div class="mk-empty">当前已接入日历中，没有可确认的七天内事件。<br>这不代表没有重要事件。</div>'}</div><details class="mk-detail"><summary>覆盖范围与日历状态</summary>${sources.map(c=>`<p>${link(c.home,c.name)}<br><span class="mk-muted">${e(c.error||'日程已读取')} · ${e(stamp(c.updatedAt))}${c.coverageThrough?'<br>日程最晚覆盖：'+e(c.coverageThrough.slice(0,10)):''}</span></p>`).join('')||'<p>连接后显示官方日历状态。</p>'}<p class="mk-muted">当前接入 FOMC、BEA、BLS 日历；不包含所有国家、公司财报或能源报告日程。只提供日期的事项不猜测具体时刻。</p>${link('https://www.eia.gov/petroleum/supply/weekly/schedule.php','EIA 能源报告日程')}</details></aside>`;}
  function sector(s,state){const q=state.snapshot?.quotes?.find(q=>q.id===s.id),v=q?.data,b=state.snapshot?.benchmark,delta=!q?.stale&&!b?.stale?JING_MARKET_RULES.relativePerformance(v,b?.data,'week'):null;const news=JING_MARKET_RULES.groupNews((state.snapshot?.news||[]).filter(n=>n.sectors?.includes(s.id)&&n.publishedAt&&Date.now()-Date.parse(n.publishedAt)<=7*86400000)).slice(0,2);let chart='';if(v?.history?.length>1){const rows=v.history,lo=Math.min(...rows.map(x=>x.close)),range=Math.max(...rows.map(x=>x.close))-lo||1;chart=`<svg viewBox="0 0 300 44" role="img" aria-label="${e(s.name)}最近收盘走势"><polyline points="${rows.map((x,i)=>`${i/(rows.length-1)*300},${38-(x.close-lo)/range*32}`).join(' ')}" fill="none" stroke="currentColor" stroke-width="2"/></svg>`;}
    return `<article class="mk-sector"><div class="mk-sector-head"><h4>${e(s.name)}</h4><span class="mk-symbol">${s.symbol}</span></div><p class="mk-muted mk-proxy">${e(s.scope)}</p><div class="mk-returns">${[['day','1 日'],['week','5 日'],['month','20 日']].map(([k,label])=>`<div>${label}<b class="${v?.changes[k]>0?'mk-up':v?.changes[k]<0?'mk-down':''}">${pct(v?.changes[k])}</b></div>`).join('')}</div>${chart}<p class="mk-benchmark">${delta===null?'同期参照：SPY 数据缺失、过期或日期不一致，暂不比较':`近 5 个交易日相对 SPY ${delta>0?'+':''}${delta.toFixed(2)} 个百分点`}</p><div class="mk-muted">${v?`${e(v.source)} · ${e(v.date)} · 收盘 USD ${Number(v.close).toFixed(2)}${q.stale||Date.now()-Date.parse(v.date)>4*86400000?' · 历史数据，非当前报价':''}`:e(q?.error||'行情待连接')+' · 暂无涨跌数据'}</div><div class="mk-sector-news"><b>近期相关消息</b>${news.map(n=>link(n.url,n.title)).join('')||'<p class="mk-muted">已接入来源中暂无近七天匹配消息。</p>'}</div><details class="mk-detail"><summary>观察重点与指标说明</summary><p>${e(s.watch)}</p><p class="mk-muted">${e(v?.basis||'未复权收盘变化，不含分红；拆股可能影响结果。')} 全部美元计价，日指交易日。SPY 是美股大盘统一参照，不是该行业或中国市场的指数。消息关联按关键词，不代表涨跌原因。</p></details><div class="mk-actions">${button('sectorNews','板块消息',s.id)}${link('https://finance.yahoo.com/quote/'+s.symbol+'/','外部行情','mk-muted')}</div></article>`;
  }
  function shell({state,error,storageError,busy,category,days,query,categories}){const s=state.snapshot,failed=s?.sources?.filter(x=>x.error)||[];return `<header class="mk-head"><div><span class="mk-eyebrow">JING WORKSPACE / MARKETS</span><h2>全球市场观察<span class="mk-title-dot"></span></h2><p class="mk-muted">重要变化，先看清楚。 <span>再形成自己的判断。</span></p></div><div class="mk-actions">${button('settings','管理关注与连接')}<button class="btn mk-refresh" data-mk="refresh" ${busy?'disabled':''}>${busy?'更新中…':'刷新消息'}</button></div></header><div class="mk-connection ${error||storageError?'mk-warn':''}" role="status"><span class="mk-live-dot"></span>${storageError?e(storageError)+' ':''}${error?e(error)+' ':''}${s?'最近检查 '+e(stamp(s.fetchedAt))+' · 北京时间':'尚未读取在线数据'}${failed.length?' · '+failed.length+' 个新闻源暂不可用':''}<a href="#mkSources">查看来源状态</a></div>
      <div class="mk-dashboard-layout">${highlights(state)}
      <section class="mk-panel mk-feed"><div class="mk-section-heading"><div><span class="mk-eyebrow">NEWS & CONTEXT</span><h3>国际与宏观消息</h3></div><span class="mk-muted">事实与解读分开看</span></div><div class="mk-filters"><select id="mkCategory" aria-label="消息主题">${Object.entries({...categories,...Object.fromEntries(state.sectors.map(id=>['sector:'+id,JING_MARKET_CATALOG.find(s=>s.id===id).name+' · 相关消息']))}).map(([id,label])=>`<option value="${id}" ${id===category?'selected':''}>${e(label)}</option>`).join('')}</select><select id="mkDays" aria-label="消息时间">${[[1,'过去 24 小时'],[7,'过去 7 天'],[30,'过去 30 天'],[0,'订阅源全部']].map(([v,label])=>`<option value="${v}" ${days===v?'selected':''}>${label}</option>`).join('')}</select><input type="search" id="mkSearch" aria-label="搜索消息" value="${e(query)}" placeholder="搜索标题、来源或关键词"></div><div id="mkNews"></div></section>
      ${timeline(state)}
      <section class="mk-following"><div class="mk-section-heading"><div><span class="mk-eyebrow">YOUR WATCHLIST</span><h3>我的关注板块 <span>趋势、消息与下一步观察</span></h3></div>${button('settings','编辑关注')}</div>${!s?.quoteConfigured?'<p class="mk-data-notice">行情待连接：目前不显示演示数字。配置服务器行情服务后，这里会显示收盘趋势和同期参照。</p>':''}<div class="mk-sector-grid">${state.sectors.map(id=>JING_MARKET_CATALOG.find(c=>c.id===id)).map(c=>sector(c,state)).join('')||'<p class="mk-empty">选择你真正关心的板块，建议先从 3–5 个开始。</p>'}</div></section></div>
      <details class="mk-panel mk-saved"><summary><span>我的收藏与观察笔记</span><span class="mk-muted">${Object.keys(state.saved).length} 条收藏 · 点击展开</span></summary><div id="mkSaved"></div></details>
      <details id="mkSources" class="mk-panel mk-sources"><summary>数据来源与连接状态 <span class="mk-muted">${s?.sources?.length||0} 个新闻源</span></summary><div class="mk-source-grid">${s?.sources?.map(source=>`<div>${link(source.home,source.name)}<p class="mk-muted">${e(source.error||source.count+' 条订阅信息')}<br>成功读取：${e(stamp(source.updatedAt))}</p></div>`).join('')||'<p>连接后显示每个来源的读取状态。</p>'}</div><p class="mk-muted">公开订阅并非全网覆盖；中国与香港目前以香港金管局为补充，公司公告目前以 Apple 为补充。无日期消息请在“订阅源全部”查看。打开 Markets 时检查新数据，停留期间每 15 分钟更新；不在关闭页面后自动运行。仅作信息观察，不自动交易。</p>${button('holdings','原有持仓笔记')}</details>`;}
  globalThis.JING_MARKET_VIEW={shell,article};
})();
