/* Markets uses public-source snapshots. No provider credentials live in the browser. */
(() => {
  const root=document.getElementById('markets');if(!root)return;
  const catalog=globalThis.JING_MARKET_CATALOG,key='jingMarketsV1',e=escapeText;
  const categories={all:'全部消息',rates:'央行与利率',economy:'通胀与经济',energy:'能源与商品',world:'国际与贸易',china:'中国与香港',company:'行业与公司',following:'关注板块',saved:'我的收藏'};
  let state={version:1,sectors:['technology','semiconductors','energy','gold'],saved:{},notes:{},analysis:{},snapshot:null};
  let storageError='',storageBlocked=false,busy=false,error='',category='all',days=7,query='',limit=20,explainBusy=null;
  try{const s=JSON.parse(localStorage.getItem(key)||'null');if(s?.version===1){state={...state,...s};state.sectors=Array.isArray(s.sectors)?s.sectors.filter(id=>catalog.some(c=>c.id===id)):state.sectors;for(const k of ['saved','notes','analysis'])if(!state[k]||Array.isArray(state[k])||typeof state[k]!=='object')state[k]={};if(state.snapshot&&!Array.isArray(state.snapshot.news))state.snapshot=null;}else if(s)throw Error('版本不兼容');}catch{storageBlocked=true;storageError='无法读取本地市场数据。原数据未覆盖；请先备份浏览器数据。';}
  const safeURL=url=>{try{const u=new URL(url);return u.protocol==='https:'&&!u.username&&!u.password?u.href:'#';}catch{return '#';}};
  const date=value=>value&&Number.isFinite(Date.parse(value))?new Date(value).toLocaleString('zh-CN',{year:'numeric',month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}):'未提供时间';
  function persist(next){if(storageBlocked){toast(storageError);return false;}try{localStorage.setItem(key,JSON.stringify(next));state=next;storageError='';return true;}catch{storageError='保存失败：浏览器存储不可用或空间已满。当前输入尚未保存，请复制备份后重试。';toast(storageError);return false;}}
  const commit=fn=>{const next=structuredClone(state);fn(next);return persist(next)};
  function article(id){return state.snapshot?.news.find(n=>n.id===id)||state.saved[id];}
  function percent(value){return Number.isFinite(value)?`${value>0?'+':''}${value.toFixed(2)}%`:'—';}
  function quote(id){return state.snapshot?.quotes?.find(q=>q.id===id);}
  function filtered(){
    const list=JING_MARKET_RULES.groupNews(category==='saved'?Object.values(state.saved):(state.snapshot?.news||[]));
    return list.filter(n=>{
      if(category!=='saved'&&days&&(!n.publishedAt||Date.now()-Date.parse(n.publishedAt)>days*86400000||Date.parse(n.publishedAt)>Date.now()+3600000))return false;
      if(category==='following'&&!n.sectors?.some(s=>state.sectors.includes(s)))return false;
      if(category.startsWith('sector:')){if(!n.sectors?.includes(category.slice(7)))return false;}
      else if(!['all','following','saved'].includes(category)&&n.category!==category)return false;
      return (n.title+' '+n.snippet+' '+n.source).toLowerCase().includes(query.toLowerCase());
    });
  }
  function spark(q){const rows=q?.data?.history;if(!Array.isArray(rows)||rows.length<2)return '';const nums=rows.map(r=>r.close),low=Math.min(...nums),range=Math.max(...nums)-low||1;return `<svg viewBox="0 0 300 42" role="img" aria-label="最近交易日收盘价走势"><polyline points="${nums.map((n,i)=>`${i/(nums.length-1)*300},${37-(n-low)/range*32}`).join(' ')}" fill="none" stroke="${nums.at(-1)>=nums[0]?'#438967':'#b76d78'}" stroke-width="2"/></svg>`;}
  function sectorHTML(s){const q=quote(s.id),v=q?.data,old=v&&Date.now()-Date.parse(v.date)>4*86400000;return `<div class="mk-sector"><div class="mk-sector-head"><b>${e(s.name)}</b><span>${e(s.symbol)}</span></div><div class="mk-muted">${e(s.scope)}</div>${v?`<div class="mk-returns">${[['day','1 个交易日'],['week','5 个交易日'],['month','20 个交易日']].map(([k,label])=>`<div>${label}<b class="${v.changes[k]>0?'mk-up':v.changes[k]<0?'mk-down':''}">${percent(v.changes[k])}</b></div>`).join('')}</div>${spark(q)}<div class="mk-muted">${e(v.source)} · 收盘 USD ${Number(v.close).toFixed(2)} · ${e(v.date)}${q.stale||old?' · ⚠ 历史数据，非当前报价':''}<br>${e(v.basis)}</div>`:`<p class="mk-muted">${e(q?.error||'行情待连接')} · 暂无涨跌数据</p>`}<p class="mk-muted">观察重点（一般机制）：${e(s.watch)}</p><div class="mk-actions"><button class="btn ghost" data-mk="sectorNews" data-id="${s.id}">相关消息</button><a class="mk-muted" href="https://finance.yahoo.com/quote/${s.symbol}/" target="_blank" rel="noopener noreferrer">外部行情 ↗</a></div></div>`;}
  function newsHTML(n){return JING_MARKET_VIEW.article(n,state,explainBusy)}
  function renderNews(){const list=filtered(),el=document.getElementById('mkNews');if(!el)return;el.innerHTML=`<p class="mk-muted">${category==='saved'?'收藏不受时间筛选限制':'按发布时间排序 · 相似报道已合并'} · ${list.length} 条</p>${list.slice(0,limit).map(newsHTML).join('')||'<div class="mk-empty">当前筛选下没有可读消息。可以扩大时间范围或检查来源连接；这不代表没有市场事件。</div>'}${list.length>limit?'<button class="btn ghost" data-mk="more">显示更多</button>':''}`;const saved=document.getElementById('mkSaved');if(saved)saved.innerHTML=Object.values(state.saved).map(newsHTML).join('')||'<p class="mk-empty">收藏值得回看的消息，记录你自己的判断。</p>';}
  function render(){
    root.innerHTML=JING_MARKET_VIEW.shell({state,error,storageError,busy,category,days,query,categories});
    root.querySelector('#mkCategory').onchange=ev=>{category=ev.target.value;limit=20;renderNews()};
    root.querySelector('#mkDays').onchange=ev=>{days=Number(ev.target.value);limit=20;renderNews()};
    root.querySelector('#mkSearch').oninput=ev=>{query=ev.target.value;limit=20;renderNews()};
    renderNews();
  }
  async function refresh(){if(busy)return;busy=true;error='';render();try{const snapshot=await requestMarketSnapshot(state.sectors);if(!Array.isArray(snapshot.news)||!Array.isArray(snapshot.sources)||!Array.isArray(snapshot.quotes))throw new Error('市场数据格式无效，请更新后端。');if(!commit(s=>{s.snapshot=snapshot}))state.snapshot=snapshot;}catch(err){error='更新失败：'+(err.message||'无法连接服务器')+'。已有缓存保留，请检查连接设置；缓存不是实时信息。';}finally{busy=false;render()}}
  function settings(){openModal(`<h2>我的市场观察</h2><p>这些是可修改的初始选项，不代表你的实际持仓。所有趋势均使用下列美国上市 ETF 作为代理。</p><div class="mk-settings">${catalog.map(s=>`<label><input type="checkbox" name="mkSector" value="${s.id}" ${state.sectors.includes(s.id)?'checked':''}><span>${e(s.name)} · ${s.symbol}<small>${e(s.scope)}</small></span></label>`).join('')}</div><button class="btn" id="mkSaveSettings">保存关注</button><hr><h3>安全连接</h3><p>公开新闻通过现有私人服务器读取，不需要新闻 API Key。行情需要在服务器秘密设置中配置 <b>ALPHA_VANTAGE_API_KEY</b>。不要在网页、HTML 或笔记里粘贴密钥。</p><p class="small">行情按每个 ETF 缓存 12 小时，可能受服务套餐、额度与网络限制。中文解读使用现有 DeepSeek 连接，点击时单独征求发送公开摘要的同意。直接打开本地 HTML 时，在线服务可能被浏览器来源限制；请使用同源的私人工作台。</p><button class="btn ghost" id="mkOpenConnection">打开现有连接设置</button><p class="small">本地收藏、笔记及关注列表保存在此浏览器。更换网址或浏览器不会自动迁移。</p>`);document.getElementById('mkSaveSettings').onclick=()=>{const ids=[...document.querySelectorAll('input[name=mkSector]:checked')].map(n=>n.value);if(commit(s=>{s.sectors=ids})){closeModal();render();refresh()}};document.getElementById('mkOpenConnection').onclick=()=>openWorkspaceConnection();}
  function editNote(id){const n=article(id);if(!n)return;openModal(`<h2>我的观察笔记</h2><p>${e(n.title)}</p><textarea id="mkNoteText" maxlength="12000" style="width:100%;min-height:180px" placeholder="这条消息为什么值得关注？下一步想核实什么？">${e(state.notes[id]||'')}</textarea><p class="small" id="mkNoteStatus">保存后自动收藏此消息，新闻退出订阅列表后笔记仍保留。</p><button class="btn" id="mkSaveNote">保存笔记</button><button class="btn ghost" id="mkDeleteNote">删除笔记</button>`);document.getElementById('mkSaveNote').onclick=()=>{const text=document.getElementById('mkNoteText').value;if(commit(s=>{s.notes[id]=text;s.saved[id]=n})){closeModal();renderNews()}else document.getElementById('mkNoteStatus').textContent=storageError;};document.getElementById('mkDeleteNote').onclick=()=>{if(confirm('删除这条个人笔记？新闻收藏会保留。')&&commit(s=>{delete s.notes[id]})){closeModal();renderNews()}};}
  async function explain(id){if(explainBusy)return;const n=article(id);if(!n)return;if(!confirm('将这条公开新闻的标题、订阅源摘要和关注板块发送到现有私人后端及 DeepSeek，生成中文解读。不发送邮件、笔记或持仓。AI 只读取摘要，可能理解有误。是否继续？'))return;explainBusy=id;renderNews();try{const result=await requestMarketExplanation({articleId:id,sectors:state.sectors,consent:true});if(result.articleId!==id)throw new Error('返回来源不匹配');if(commit(s=>{s.analysis[id]=result;s.saved[id]=n}))toast('解读已保存，请结合原文核实');}catch(err){toast('解读失败：'+err.message+'；未生成替代内容。')}finally{explainBusy=null;renderNews()}}
  root.addEventListener('click',ev=>{const b=ev.target.closest('[data-mk]');if(!b)return;const id=b.dataset.id;switch(b.dataset.mk){case 'focusArticle':{category='all';days=0;query='';limit=200;render();const target=[...root.querySelectorAll('#mkNews [data-article]')].find(n=>n.dataset.article===id);if(target){target.querySelector('details').open=true;target.scrollIntoView({behavior:'smooth',block:'center'});}break;}case 'refresh':refresh();break;case 'settings':settings();break;case 'category':category=id;days=0;query='';limit=20;render();break;case 'sectorNews':category='sector:'+id;days=0;query='';limit=20;render();break;case 'holdings':holdings();break;case 'more':limit+=20;renderNews();break;case 'save':{const n=article(id);if(!n)break;if(state.saved[id]&&(state.notes[id]||state.analysis[id])){toast('此收藏含有笔记或解读，请先删除它们再取消收藏。');break;}if(commit(s=>{if(s.saved[id])delete s.saved[id];else s.saved[id]=n}))renderNews();break;}case 'note':editNote(id);break;case 'explain':explain(id);break;case 'deleteAI':if(commit(s=>{delete s.analysis[id]}))renderNews();break;}});
  function holdings(){const ids=Object.keys(workspaceState.stocks||{});openModal(`<h2>原有持仓笔记</h2><p>记录原样保留；未接入单股报价，不使用演示价格估值。</p>${ids.length?ids.map(id=>`<button class="btn ghost" data-mk-stock="${e(id)}">${e(id)}</button>`).join(' '):'<p>没有已保存的持仓笔记。</p>'}`);document.querySelectorAll('[data-mk-stock]').forEach(b=>b.onclick=()=>openMarketHolding(b.dataset.mkStock));}

  const previousGo=window.go;window.go=function(id){const result=previousGo.apply(this,arguments);if(id==='markets'){render();if(!state.snapshot||state.snapshot.schemaVersion!==2||Date.now()-Date.parse(state.snapshot.fetchedAt)>15*60000)refresh()}return result};

  // Preserve saved holdings but do not value them using the old demo prices.
  function openMarketHolding(t){const saved=workspaceState.stocks[t]||{};openModal(`<h2>${e(t)} · 持仓笔记</h2><p>已保留原有记录。未连接此股票的真实报价，不计算盈亏。</p><label>平均成本<input class="form-input" id="mkStockCost" type="number" min="0" value="${e(saved.cost||'')}"></label><label>数量<input class="form-input" id="mkStockShares" type="number" min="0" value="${e(saved.shares||'')}"></label><label>个人观察<textarea id="mkStockThesis">${e(saved.thesis||'')}</textarea></label><button class="btn" id="mkSaveStock">保存</button>`);document.getElementById('mkSaveStock').onclick=()=>{workspaceState.stocks[t]={...saved,cost:document.getElementById('mkStockCost').value,shares:document.getElementById('mkStockShares').value,thesis:document.getElementById('mkStockThesis').value};if(saveWorkspaceState()!==false){closeModal();toast('持仓笔记已保存')}}};
  setInterval(()=>{if(!document.hidden&&root.classList.contains('active'))refresh()},15*60000);
  window.addEventListener('storage',ev=>{if(ev.key===key){try{const s=JSON.parse(ev.newValue);if(s?.version===1&&Array.isArray(s.sectors)&&s.sectors.every(id=>catalog.some(c=>c.id===id))){state=s;render()}}catch{}}});
  render();
})();
