/* Papers: local PDF library, anchored annotations and source-grounded AI. */
(() => {
  'use strict';
  const KEY='papers-v2-state', MAX_FILE=40*1024*1024;
  const colors={yellow:'#efc74a',blue:'#65a7f0',green:'#68bd92',pink:'#e38eac',purple:'#ab8ae3'};
  const colorNames={yellow:'重要观点',blue:'研究方法',green:'可用证据',pink:'局限',purple:'疑问'};
  const fields=['研究问题','理论','研究方法','样本','主要发现','局限'];
  const e=value=>escapeText(value??''), uid=()=>crypto.randomUUID(), clone=x=>structuredClone(x);
  let state={version:2,papers:[],comparisons:[]}, ready=false, queue=Promise.resolve(), reader=null, pdf=null, renderTask=null, renderSerial=0, selected=null, aiBusy=false;
  let query='',courseFilter='',statusFilter='', side='understand', mobile='document', editor=null, lastError='', saveNumber=0;
  const noteDrafts=new Map();let pendingWrites=0;
  const byId=id=>state.papers.find(p=>p.id===id);
  const $=id=>document.getElementById(id);
  const button=(label,action,id='',extra='')=>`<button class="btn ghost" data-paper-action="${action}" data-id="${e(id)}" ${extra}>${label}</button>`;
  const options=(values,current)=>values.map(([v,label])=>`<option value="${e(v)}" ${v===current?'selected':''}>${e(label)}</option>`).join('');
  const courses=()=>[['Unlinked','未关联课程'],...Object.keys(courseCatalog).map(c=>[c,c])];
  const statuses=[['Queued','待读'],['Reading','阅读中'],['Completed','已读完'],['Priority','优先阅读']];
  function assignments(){return [...Object.entries(assignmentCatalog).map(([id,a])=>['catalog:'+id,a.course+' · '+a.title]),...(workspaceState.customAssignments||[]).map(a=>['custom:'+a.id,(a.course||'')+' · '+a.title]),...(workspaceState.generatedAssignments||[]).map(a=>['generated:'+a.id,(a.course||'')+' · '+a.title])];}
  function assignmentLabel(id){return assignments().find(a=>a[0]===id)?.[1]||(id?'原作业已移除（保留关联记录）':'未关联作业');}
  function normalize(p){return {...p,id:String(p.id||uid()),title:String(p.title||''),authors:String(p.authors||''),year:String(p.year||''),status:p.status||'Queued',course:p.course||'Unlinked',notes:p.notes||'',pages:p.pages||[],page:Number.isInteger(p.page)&&p.page>0?p.page:1,furthest:Number.isInteger(p.furthest)&&p.furthest>=0?p.furthest:0,zoom:Number.isFinite(p.zoom)&&p.zoom>=.25&&p.zoom<=3?p.zoom:1,highlights:(p.highlights||[]).map(h=>({...h,id:h.id||uid(),text:h.text||'',rects:h.rects||[],color:colors[h.color]?h.color:'yellow'})),evidence:p.evidence||[],analyses:p.analyses||[],fileDeleted:Boolean(p.fileDeleted)};}
  async function dbRead(key){const db=await openWorkspaceFileDB();try{return await new Promise((resolve,reject)=>{const tx=db.transaction('files'),r=tx.objectStore('files').get(key);r.onsuccess=()=>resolve(r.result);r.onerror=()=>reject(r.error)})}finally{db.close()}}
  async function write(next,puts=[],removes=[]){
    const db=await openWorkspaceFileDB();try{await new Promise((resolve,reject)=>{const tx=db.transaction('files','readwrite'),s=tx.objectStore('files');s.put(next,KEY);for(const [key,value]of puts)s.put(value,key);for(const key of removes)s.delete(key);tx.oncomplete=resolve;tx.onabort=tx.onerror=()=>reject(tx.error||new Error('本地存储事务失败'))})}finally{db.close()}
  }
  function project(){
    workspaceState.papers=state.papers.filter(p=>!p.fileDeleted).map(p=>{const {pages,analyses,evidence,highlights,...meta}=p;return {...meta,notes:p.notes,highlights:highlights.map(h=>({id:h.id,text:h.text,color:h.color,page:h.page})),paperEngine:2}});
    try{localStorage.setItem('jingWorkspaceStateV1',JSON.stringify(workspaceState))}catch{notice('文献已保存，但首页摘要缓存写入失败；请导出备份并检查浏览器空间。',true)}
    if(typeof renderDashboard==='function')renderDashboard();
  }
  function commit(change,puts=[],removes=[]){
    pendingWrites++;
    const job=queue.then(async()=>{if(!ready)throw new Error('文献库尚未就绪，请刷新后重试。');const run=async()=>{const next=clone(await dbRead(KEY)||state);await change(next);await write(next,puts,removes);state=next;project();renderPapers();return next};return location.protocol!=='file:'&&navigator.locks? navigator.locks.request('jing-papers-v2-write',run):run()}).finally(()=>pendingWrites--);queue=job.catch(()=>{});return job;
  }
  function notice(text,error=false){let n=$('paperLibraryStatus');if(n){n.textContent=text;n.className=error?'paper-error':'paper-notice'}else toast(text)}
  function saved(text,error=false){const n=$('paperSave');if(n){n.textContent=text;n.style.color=error?'#a02d38':''}}
  function errorText(err){return err?.name==='QuotaExceededError'?'浏览器空间不足，未保存。请导出备份并释放空间后重试。':err?.message||'保存失败，请重试。'}
  async function saveInput(id,key,value){const number=++saveNumber;if(key==='notes')noteDrafts.set(id,value);saved('正在保存…');try{await commit(s=>{const p=s.papers.find(p=>p.id===id);if(p)p[key]=value});if(key==='notes'&&noteDrafts.get(id)===value)noteDrafts.delete(id);if(number===saveNumber){saved('已保存到此浏览器');lastError=''}}catch(err){lastError=errorText(err);saved(lastError,true)}}
  function buildLibrary(){
    const tools=document.createElement('div');tools.className='paper-tools';tools.innerHTML=`<input class="form-input" id="paperSearch" placeholder="搜索标题、作者、年份或笔记" aria-label="搜索文献"><select class="form-select" id="paperCourseFilter" aria-label="按课程筛选">${options([['','所有课程'],...courses()],courseFilter)}</select><select class="form-select" id="paperStatusFilter" aria-label="按状态筛选">${options([['','所有状态'],...statuses,['retained','原文件已删除']],statusFilter)}</select>${button('导出备份','export')}${button('导入备份','import-backup')}<input id="paperBackupFile" hidden type="file" accept=".zip"><div id="paperLibraryStatus" class="paper-notice" role="status" style="flex-basis:100%">PDF、笔记和标记保存在当前浏览器；可导出包含原文件的备份。</div>`;
    document.querySelector('#papers .toolbar').after(tools);
    $('paperSearch').oninput=ev=>{query=ev.target.value;renderPapers()};$('paperCourseFilter').onchange=ev=>{courseFilter=ev.target.value;renderPapers()};$('paperStatusFilter').onchange=ev=>{statusFilter=ev.target.value;renderPapers()};
    $('paperBackupFile').onchange=ev=>{const f=ev.target.files[0];if(f)restore(f);ev.target.value=''};
  }
  renderPapers=function(){if(!ready)return;const list=state.papers.filter(p=>(!query||(p.title+' '+p.authors+' '+p.year+' '+p.notes).toLowerCase().includes(query.toLowerCase()))&&(!courseFilter||p.course===courseFilter)&&(!statusFilter||(statusFilter==='retained'?p.fileDeleted:!p.fileDeleted&&p.status===statusFilter)));
    $('papersQueue').innerHTML=list.length?list.map(p=>`<div class="paper-row file-row paper-library-row"><div><button class="paper-link" style="background:none;border:0;text-align:left;cursor:pointer" data-paper-action="open" data-id="${e(p.id)}"><b>${e(p.title||'未填写标题')}</b></button><div class="small">${e(p.authors||'作者未填写')} · ${e(p.year||'年份未填写')} · ${e(p.course)}</div><div class="small">${p.fileDeleted?'原文件已删除 · 笔记与证据已保留':`${e(statuses.find(x=>x[0]===p.status)?.[1]||p.status)} · ${p.pages.length?`${p.page}/${p.pages.length} 页 · 已浏览 ${Math.round((p.furthest||0)/p.pages.length*100)}%`:'未解析'}`}</div>${!p.fileName?'<span class="badge">无来源文件 · 旧记录</span>':''}</div>${button('阅读','open',p.id)}${button('编辑','metadata',p.id)}${button('删除','delete',p.id)}</div>`).join(''):'<div class="paper-empty">没有匹配的文献。上传 PDF，或调整筛选条件。</div>';
    $('paperCountBadge').textContent=state.papers.filter(p=>!p.fileDeleted).length+' papers';
    const all=state.papers.flatMap(p=>p.evidence.map(r=>({p,r})));$('paperEvidenceCount').textContent=all.length;
    $('paperEvidenceList').innerHTML=all.length?all.map(({p,r})=>`<div class="paper-record"><b>${e(p.title)}</b><div class="small">p.${r.page||'—'} ${p.fileDeleted?'· 原文件已删除':''}</div><blockquote>${e(r.text)}</blockquote><p>${e(r.claim||r.note||'尚未填写观点')}</p><div class="small">${e(r.course||p.course)} · ${e(assignmentLabel(r.assignment))}</div><div class="paper-evidence-actions">${button('查看 / 编辑','evidence-open',p.id,`data-record="${e(r.id)}"`)}${button('查看作业','assignment','',`data-assignment="${e(r.assignment||'')}"`)}</div></div>`).join(''):'<div class="paper-empty">阅读时选中原文，保存为证据，再关联课程或作业。</div>';
  };
  async function parsePDF(file){
    if(file.size>MAX_FILE)throw new Error('单份 PDF 限 40 MB，请压缩后上传。');
    if(!/\.pdf$/i.test(file.name||'')&&file.type!=='application/pdf')throw new Error('此入口支持 PDF；旧记录及其文件仍可打开。');
    const doc=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;
    try{if(doc.numPages>500)throw new Error('单份 PDF 限 500 页，请分卷上传。');const pages=[];
      for(let i=1;i<=doc.numPages;i++){const pg=await doc.getPage(i),c=await pg.getTextContent();pages.push({page:i,text:c.items.map(x=>(x.str||'')+(x.hasEOL?'\n':' ')).join('').trim()});}
      const meta=await doc.getMetadata().catch(()=>({info:{}})),info=meta.info||{};
      return {pages,title:info.Title&&!/^untitled$/i.test(info.Title)?info.Title:'',authors:info.Author&&!/^anonymous$/i.test(info.Author)?info.Author:'',year:'',parseStatus:pages.some(p=>p.text.trim())?'ready':'needs-ocr',metadataSource:'PDF embedded metadata'};
    }finally{await doc.destroy()}
  }
  importPaper=async function(ev){await initialized;const files=[...ev.target.files];ev.target.value='';let count=0;const failures=[];
    for(const file of files){notice('正在解析 '+file.name+'…');try{const parsed=await parsePDF(file),id=uid(),p=normalize({id,...parsed,title:parsed.title||file.name.replace(/\.pdf$/i,''),fileName:file.name,hasLocalFile:true,createdAt:new Date().toISOString()});await commit(s=>s.papers.push(p),[['paper-'+id,file]]);count++}catch(err){failures.push(file.name+'：'+errorText(err))}}
    notice(`已保存 ${count} 份 PDF。${failures.length?'\n'+failures.join('\n'):''}`,Boolean(failures.length));
  };
  function metadata(id){const p=byId(id);if(!p)return;closeReader();openModal(`<h2>编辑文献信息</h2><p class="small">自动识别仅使用 PDF 内嵌信息；请核对作者和标题。年份不会从文件创建时间推断。</p>${[['title','标题'],['authors','作者'],['year','出版年份']].map(([k,label])=>`<div class="field"><label>${label}</label><input class="form-input" id="paperMeta-${k}" value="${e(p[k])}" maxlength="${k==='year'?4:1000}"></div>`).join('')}<div class="field"><label>关联课程</label><select class="form-select" id="paperMeta-course">${options(courses(),p.course)}</select></div><div class="field"><label>阅读状态</label><select class="form-select" id="paperMeta-status">${options(statuses,p.status)}</select></div><div id="paperMetaError" role="alert"></div>${button('保存','metadata-save',id)}`)}
  function readerShell(p){
    let root=$('paperReader');if(!root){root=document.createElement('section');root.id='paperReader';root.className='paper-reader';root.setAttribute('aria-label','文献阅读工作台');document.body.append(root)}
    root.hidden=false;root.dataset.mobile=mobile;root.innerHTML=`<header>${button('← 文献库','close')}<h2>${e(p.title)}</h2><span id="paperSave" class="paper-save-state" role="status">已保存到此浏览器</span>${button('编辑资料','metadata',p.id)}</header><nav class="paper-mobile-nav">${button('原文','mobile','document')}${button('笔记','mobile','notes')}${button('解读','mobile','understand')}</nav><div class="reader-layout"><div class="paper-document"><div class="reader-toolbar">${button('←','page-prev')}<input id="paperPageNumber" aria-label="页码" type="number" min="1" max="${p.pages.length||1}" value="${p.page}"><span id="paperTotalPages">/ ${p.pages.length||'—'}</span>${button('→','page-next')}${button('−','zoom-out')}<span id="paperZoom">${Math.round(p.zoom*100)}%</span>${button('＋','zoom-in')}${button('适合宽度','fit')}${button('打开原文件','original',p.id)}</div><div class="pdf-scroll" id="paperPdfScroll"><div id="paperPdfStatus" class="paper-empty">正在打开 PDF…</div><div class="paper-page" id="paperPage"><canvas id="paperCanvas"></canvas><div id="paperMarks" class="paper-mark-layer"></div><div id="paperText" class="paper-text-layer"></div></div></div></div><aside class="paper-side"><nav class="paper-side-nav">${button('理解这篇文献','side','understand',`aria-selected="${side==='understand'}"`)}${button('我的笔记','side','notes',`aria-selected="${side==='notes'}"`)}${button('可用证据','side','evidence',`aria-selected="${side==='evidence'}"`)}</nav><div id="paperSideBody"></div></aside></div>`;
    $('paperPageNumber').onchange=ev=>goPage(Number(ev.target.value));document.body.style.overflow='hidden';renderSide();
  }
  function closeReader(){renderSerial++;renderTask?.cancel();renderTask=null;if(pdf){pdf.destroy();pdf=null}reader=null;selected=null;editor=null;const root=$('paperReader');if(root)root.hidden=true;document.body.style.overflow='';}
  openPaper=async function(id){await initialized;const p=byId(id);if(!p)return;closeModal();closeReader();reader=id;side='understand';mobile='document';lastError='';readerShell(p);const current=id;
    try{if(p.fileDeleted)throw new Error('原文件已删除。保留的笔记、证据和分析仍可查看与导出。');const file=await dbRead('paper-'+id);if(!file)throw new Error('此记录没有本地原文件；请重新上传 PDF。原有笔记已保留。');
      if(!/\.pdf$/i.test(p.fileName||'')&&file.type!=='application/pdf')throw new Error('旧格式文件可通过“打开原文件”下载；内嵌阅读支持 PDF。');
      const loaded=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise;if(reader!==current){loaded.destroy();return}pdf=loaded;
      if(!p.pages.length){const parsed=await parsePDF(new File([file],p.fileName,{type:'application/pdf'}));await commit(s=>Object.assign(s.papers.find(x=>x.id===id),{pages:parsed.pages,parseStatus:parsed.parseStatus}));}
      if(reader!==current)return;$('paperTotalPages').textContent='/ '+pdf.numPages;$('paperPageNumber').max=pdf.numPages;renderSide();await renderPage();await commit(s=>{const q=s.papers.find(x=>x.id===id);if(q){if(q.status==='Queued')q.status='Reading';q.furthest=Math.max(q.furthest||0,q.page)}});
    }catch(err){if(reader!==current)return;$('paperPage').hidden=true;$('paperPdfStatus').textContent=errorText(err);$('paperPdfStatus').className='paper-error';}
  };
  async function goPage(value){const p=byId(reader);if(!p||!pdf)return;const page=Math.max(1,Math.min(pdf.numPages,Math.round(value)||1));await saveInput(p.id,'page',page);await commit(s=>{const q=s.papers.find(x=>x.id===p.id);q.furthest=Math.max(q.furthest||1,page)});selected=null;editor=null;renderSide();await renderPage();}
  async function renderPage(focusId){
    if(!pdf||!reader)return;const serial=++renderSerial,p=byId(reader),doc=pdf;renderTask?.cancel();
    try{const page=await doc.getPage(p.page);if(serial!==renderSerial)return;const viewport=page.getViewport({scale:p.zoom}),dpr=Math.min(window.devicePixelRatio||1,2),canvas=$('paperCanvas'),box=$('paperPage'),layer=$('paperText');
      box.hidden=false;box.style.width=viewport.width+'px';box.style.height=viewport.height+'px';canvas.width=Math.ceil(viewport.width*dpr);canvas.height=Math.ceil(viewport.height*dpr);canvas.style.width=viewport.width+'px';canvas.style.height=viewport.height+'px';layer.replaceChildren();
      renderTask=page.render({canvasContext:canvas.getContext('2d'),viewport,transform:dpr===1?null:[dpr,0,0,dpr,0,0]});await renderTask.promise;if(serial!==renderSerial)return;const content=await page.getTextContent();if(serial!==renderSerial)return;
      const measure=document.createElement('canvas').getContext('2d');
      for(const item of content.items){if(!item.str)continue;const tx=pdfjsLib.Util.transform(viewport.transform,item.transform),fontHeight=Math.hypot(tx[2],tx[3]),style=content.styles[item.fontName]||{},ascent=(style.ascent??(style.descent?1+style.descent:.8))*fontHeight,angle=Math.atan2(tx[1],tx[0]);const span=document.createElement('span');span.textContent=item.str;const font=style.fontFamily||'sans-serif';span.style.fontFamily=font;span.style.fontSize=fontHeight+'px';span.style.left=(tx[4]+ascent*Math.sin(angle))+'px';span.style.top=(tx[5]-ascent*Math.cos(angle))+'px';measure.font=fontHeight+'px '+font;const width=measure.measureText(item.str).width;span.style.transform=`rotate(${angle}rad) scaleX(${width?item.width*viewport.scale/width:1})`;layer.append(span);if(item.hasEOL)layer.append(document.createElement('br'));}
      layer.onmouseup=captureSelection;layer.onkeyup=captureSelection;layer.ontouchend=()=>setTimeout(captureSelection,100);
      $('paperPageNumber').value=p.page;$('paperZoom').textContent=Math.round(p.zoom*100)+'%';$('paperPdfStatus').textContent=content.items.some(i=>i.str?.trim())?'选中原文可高亮、批注或保存为证据。':'本页没有可选择文字，需要 OCR；仍可阅读图像、写普通笔记。';$('paperPdfStatus').className='paper-notice';paintMarks(focusId);$('paperPdfScroll').scrollTop=0;
      if(focusId){const mark=$('paperMarks').querySelector('.located');mark?.scrollIntoView({block:'center',inline:'nearest'})}
    }catch(err){if(serial!==renderSerial||err.name==='RenderingCancelledException')return;$('paperPdfStatus').textContent='页面显示失败：'+errorText(err);$('paperPdfStatus').className='paper-error'}
  }
  function paintMarks(focusId){const p=byId(reader);if(!p||!$('paperMarks'))return;const rows=[...p.highlights,...p.evidence];$('paperMarks').innerHTML=rows.filter(h=>h.page===p.page).flatMap(h=>(h.rects||[]).map(r=>`<i class="${h.id===focusId?'located':''}" style="left:${r.x*100}%;top:${r.y*100}%;width:${r.w*100}%;height:${r.h*100}%;background:${colors[h.color]||colors.green}"></i>`)).join('')}
  function captureSelection(){const sel=getSelection(),layer=$('paperText');if(!sel?.rangeCount||!sel.toString().trim()||!layer)return;const range=sel.getRangeAt(0);if(!layer.contains(range.startContainer)||!layer.contains(range.endContainer))return;const box=$('paperPage').getBoundingClientRect(),rects=[...range.getClientRects()].filter(r=>r.width>1&&r.height>1).map(r=>({x:Math.max(0,(r.left-box.left)/box.width),y:Math.max(0,(r.top-box.top)/box.height),w:Math.min(1,r.width/box.width),h:Math.min(1,r.height/box.height)}));selected={text:sel.toString().trim(),page:byId(reader).page,rects};editor=null;renderSide();}
  function selectionUI(){return selected?`<div class="paper-selection"><b>选中原文 · p.${selected.page}</b><p>${e(selected.text)}</p>${button('高亮 / 批注','annotate')}${button('保存为证据','evidence-new')}${button('解释选段','explain-selection')}</div>`:''}
  function recordUI(p,r,type){return `<div class="paper-record" style="border-left-color:${colors[r.color]||colors.green}"><div class="small">${r.page?'p.'+r.page:'旧摘录 · 无页码'} ${p.fileDeleted?'· 原文件已删除':''}</div><blockquote>${e(r.text)}</blockquote><p>${e(r.note||'')}</p>${type==='evidence'?`<b>${e(r.claim||'')}</b><div class="small">${e(r.course||p.course)} · ${e(assignmentLabel(r.assignment))}</div>`:''}<div class="actions">${button('定位原文','locate',r.id)}${button('编辑','record-edit',r.id,`data-kind="${type}"`)}${button('删除','record-delete',r.id,`data-kind="${type}"`)}${type==='evidence'?button('查看作业','assignment','',`data-assignment="${e(r.assignment||'')}"`):button('用作证据','promote',r.id)}</div></div>`}
  function editorUI(p){const r=editor.record,kind=editor.kind;const allAssignments=assignments();if(r.assignment&&!allAssignments.some(a=>a[0]===r.assignment))allAssignments.push([r.assignment,assignmentLabel(r.assignment)]);return `<div class="paper-record"><b>${kind==='evidence'?'保存可用证据':'原文高亮与批注'} · p.${r.page||'—'}</b><blockquote>${e(r.text)}</blockquote><div class="field"><label>颜色 / 用途</label><select id="paperRecordColor" class="form-select">${options(Object.keys(colors).map(c=>[c,colorNames[c]]),r.color||'yellow')}</select></div><div class="field"><label>我的批注 / 个人解释</label><textarea id="paperRecordNote">${e(r.note||'')}</textarea></div>${kind==='evidence'?`<div class="field"><label>这段可以支持什么观点？</label><textarea id="paperRecordClaim">${e(r.claim||'')}</textarea></div><div class="field"><label>关联课程</label><select id="paperRecordCourse" class="form-select">${options(courses(),r.course||p.course)}</select></div><div class="field"><label>关联作业</label><select id="paperRecordAssignment" class="form-select">${options([['','未关联作业'],...allAssignments],r.assignment||'')}</select></div>`:''}<div id="paperRecordError" role="alert"></div>${button('保存','record-save')}${button('取消','record-cancel')}</div>`}
  function renderSide(){const p=byId(reader),body=$('paperSideBody');if(!p||!body)return;document.querySelectorAll('.paper-side-nav [data-id]').forEach(b=>b.setAttribute('aria-selected',String(b.dataset.id===side)));$('paperReader').dataset.mobile=mobile;
    let html=selectionUI();if(editor)html+=editorUI(p);
    else if(side==='notes')html+=`<h3>我的笔记</h3><textarea id="paperNotes" placeholder="写下理解、疑问和想法…">${e(noteDrafts.get(p.id)??p.notes)}</textarea><p class="paper-notice">${noteDrafts.has(p.id)?'有尚未保存的笔记，请重试保存。':'自动保存到此浏览器。'}${lastError?e(lastError):''}</p>${button('重试保存笔记','retry-notes')}<h3>原文标记 · ${p.highlights.length}</h3>${p.highlights.map(r=>recordUI(p,r,'highlights')).join('')||'<div class="paper-empty">在左侧选中文字，添加第一条标记。</div>'}`;
    else if(side==='evidence')html+=`<h3>可用证据 · ${p.evidence.length}</h3><p class="paper-notice">原文、页码、你的解释和关联作业会一起保存。</p>${p.evidence.map(r=>recordUI(p,r,'evidence')).join('')||'<div class="paper-empty">选中原文并点击“保存为证据”。</div>'}`;
    else html+=analysisUI(p);
    body.innerHTML=html;const notes=$('paperNotes');if(notes)notes.oninput=ev=>saveInput(p.id,'notes',ev.target.value);
  }
  function analysisUI(p){const history=p.analyses||[],current=history.find(a=>a.id===p.activeAnalysis)||history.at(-1);return `<h3>理解这篇文献</h3><p class="paper-notice">已解析 ${p.pages.length} 页、${p.pages.reduce((n,x)=>n+x.text.length,0).toLocaleString()} 字符。${p.pages.some(x=>!x.text.trim())?'部分页面无文字；图表和扫描图像未参与分析。':''}${p.parseStatus==='needs-ocr'?'这份 PDF 需要 OCR，暂不能生成全文解读。':''}</p>${button('查看解析文字','text-preview')} ${button('AI 连接设置','connection')}<label class="check-row"><input id="paperAIConsent" type="checkbox"><span>本次将全文解析文字${selected?'及所选段落':''}发送到私人后端与 DeepSeek，用于分析。文件本身保留在本地。</span></label><div class="actions">${button(aiBusy?'分析中…':'中文解读 · 保留英文术语','analyze-summary','',aiBusy?'disabled':'')}</div><div class="field"><label>围绕原文提问</label><textarea id="paperQuestion" maxlength="2000" placeholder="例如：这项研究为什么使用这个方法？"></textarea>${button('提问','analyze-question','',aiBusy?'disabled':'')}</div><div id="paperAIStatus" class="${lastError?'paper-error':'paper-notice'}" role="status">${e(lastError)}</div>${history.length?`<label>已保存的分析版本</label><select id="paperAnalysisVersion" class="form-select" onchange="Papers.selectAnalysis(this.value)">${options(history.map(a=>[a.id,(a.mode==='question'?'问答':'解读')+' · '+new Date(a.generatedAt).toLocaleString()+(a.userEdited?' · 已手动编辑':'')]),current?.id)}</select>`:''}${current?`<p class="paper-notice">${current.userEdited?'以下结果含用户修改；来源摘录保持原样。':'AI 生成；引文已匹配解析文字，结论仍需结合原文核对。'}</p>${current.sections.map((s,i)=>`<div class="paper-record"><h4>${e(s.field)}</h4><label>原文信息 ${current.userEdited?'（可含用户修改）':''}</label><textarea data-analysis-index="${i}" data-analysis-key="text">${e(s.text)}</textarea><label>AI 解释 / 我的修改</label><textarea data-analysis-index="${i}" data-analysis-key="interpretation">${e(s.interpretation)}</textarea>${s.evidence.map(r=>`<p>${button('来源 p.'+r.page,'source',String(r.page))}<span class="source-quote">${e(r.quote)}</span></p>`).join('')}</div>`).join('')}${button('保存我的修改','analysis-save',current.id)}${button('重新生成（保留旧版本）','regenerate',current.id,aiBusy?'disabled':'')}${button('删除此版本','analysis-delete',current.id)}`:'<div class="paper-empty">尚未生成 AI 解读。普通笔记、高亮和阅读可直接使用。</div>'}`}
  async function analyze(mode,previous){const p=byId(reader);if(!p||aiBusy)return;const consent=$('paperAIConsent')?.checked;if(!consent){$('paperAIStatus').textContent='请先勾选本次文字传输确认。';return}const question=previous?.question||$('paperQuestion')?.value.trim();if(mode==='question'&&!question){$('paperAIStatus').textContent='请先输入问题。';return}if(!p.pages.some(x=>x.text.trim())){$('paperAIStatus').textContent='没有可读取的文字，扫描版需要 OCR。';return}
    // Save an edited displayed version before regeneration, and keep it in history.
    if($('paperAnalysisVersion'))await saveAnalysis($('paperAnalysisVersion').value,false);
    const target=p.id,payload={consent:true,mode,question,selection:selected?.text||previous?.selection||'',papers:[{id:p.id,title:p.title,pages:p.pages}]};aiBusy=true;lastError='';$('paperAIStatus').textContent='正在分析全文，请稍候…';
    try{const result=await requestPaperAnalysis(payload);if(result.source!=='deepseek'||!Array.isArray(result.sections))throw new Error('服务器没有返回有效文献分析，请检查后端版本。');await commit(s=>{const q=s.papers.find(x=>x.id===target);if(!q)throw new Error('文献已删除，未保存返回结果。');const a={...result,id:uid(),mode,question:question||'',selection:payload.selection};q.analyses.push(a);q.activeAnalysis=a.id});}
    catch(err){lastError=errorText(err)}finally{aiBusy=false;if(reader===target)renderSide();else if(lastError)notice(lastError,true)}
  }
  async function saveAnalysis(id,refresh=true){const p=byId(reader),a=p?.analyses.find(a=>a.id===id);if(!a)return;const sections=clone(a.sections);document.querySelectorAll('[data-analysis-index]').forEach(el=>{sections[Number(el.dataset.analysisIndex)][el.dataset.analysisKey]=el.value});if(JSON.stringify(sections)===JSON.stringify(a.sections))return;await commit(s=>{const q=s.papers.find(x=>x.id===p.id).analyses.find(x=>x.id===id);q.sections=sections;q.userEdited=true;q.editedAt=new Date().toISOString()});saved('修改已保存');if(refresh)renderSide();}
  function deletion(id){const p=byId(id);if(!p)return;closeReader();openModal(`<h2>删除文献</h2><p>${e(p.title)}</p><p class="small">${p.highlights.length} 条标记 · ${p.evidence.length} 条证据 · ${p.analyses.length} 个分析版本。保留笔记时，多篇比较仍可查看历史摘录。全部删除时，也移除此文献在比较中的内容；不足两篇的比较会移除。</p>${!p.fileDeleted?button('删除原文件，保留笔记与证据','delete-keep',id):''} ${button('删除文献及全部笔记与证据','delete-all',id)}<div id="paperDeleteError" role="alert"></div>`)}
  async function remove(id,keep){const p=byId(id);if(!p)return;await commit(s=>{if(keep){const q=s.papers.find(x=>x.id===id);q.fileDeleted=true;q.hasLocalFile=false;q.pages=[]}else{s.papers=s.papers.filter(x=>x.id!==id);for(const c of s.comparisons){c.paperIds=c.paperIds.filter(x=>x!==id);c.sections=c.sections.filter(x=>x.paperId!==id);delete c.titles[id]}s.comparisons=s.comparisons.filter(c=>c.paperIds.length>=2)}},[],['paper-'+id]);noteDrafts.delete(id);closeModal();notice(keep?'原文件已删除；笔记、标记、证据和分析已保留。':'文献、原文件、笔记、证据及关联比较内容已删除。');}
  openPaperCompare=function(){closeReader();const selectedPapers=state.papers.filter(p=>!p.fileDeleted);openModal(`<h2>Compare Papers</h2><p class="small">选择 2–5 篇文献。全文最多共 120,000 字符；不截断原文。无文字的 PDF 需先 OCR。</p>${selectedPapers.map(p=>`<label class="check-row"><input type="checkbox" name="paperCompare" value="${e(p.id)}"><span>${e(p.title)} · ${p.pages.length} 页</span></label>`).join('')}<label class="check-row"><input id="paperCompareConsent" type="checkbox"><span>将所选文献全文文字发送到私人后端与 DeepSeek。</span></label>${button('生成比较','compare-run')}${button('AI 连接设置','connection')}<div id="paperCompareStatus" role="status"></div><h3>已保存比较</h3>${state.comparisons.map(c=>`<div class="paper-row">${button(e(new Date(c.generatedAt).toLocaleString())+' · '+c.paperIds.length+' 篇','compare-open',c.id)}${button('删除','compare-delete',c.id)}</div>`).join('')||'<p class="small">尚无比较结果</p>'}`)};
  openLiteratureMatrix=()=>openPaperCompare();
  function appendAssignmentEvidence(reference){
    const rows=state.papers.flatMap(p=>p.evidence.filter(r=>r.assignment===reference).map(r=>({p,r})));if(!rows.length)return;
    const section=document.createElement('section');section.className='modal-section';section.id='assignmentPaperEvidence';section.innerHTML=`<h3>关联的文献证据 · ${rows.length}</h3>${rows.map(({p,r})=>`<div class="paper-record"><b>${e(p.title)}</b><div class="small">p.${r.page||'—'} ${p.fileDeleted?'· 原文件已删除':''}</div><blockquote>${e(r.text)}</blockquote><p>${e(r.claim||r.note||'')}</p>${button('查看原文 / 编辑证据','evidence-open',p.id,`data-record="${e(r.id)}"`)}</div>`).join('')}`;$('modalContent').append(section);
  }
  const oldAssignment=openAssignment,oldCustomAssignment=openCustomAssignment,oldGeneratedAssignment=openGeneratedAssignment;
  openAssignment=function(id='eds6001'){oldAssignment(id);appendAssignmentEvidence('catalog:'+id)};
  openCustomAssignment=function(id){oldCustomAssignment(id);appendAssignmentEvidence('custom:'+id)};
  openGeneratedAssignment=function(id){oldGeneratedAssignment(id);appendAssignmentEvidence('generated:'+id)};
  async function compare(){if(aiBusy)return;const ids=[...document.querySelectorAll('[name=paperCompare]:checked')].map(x=>x.value),consent=$('paperCompareConsent').checked;if(ids.length<2||ids.length>5)throw new Error('请选择 2–5 篇文献。');if(!consent)throw new Error('请确认本次文献文字传输。');const papers=ids.map(id=>byId(id));if(papers.some(p=>!p.pages.some(x=>x.text.trim())))throw new Error('所选文献包含未解析或无文字的文件，请先上传可读取的 PDF。');aiBusy=true;$('paperCompareStatus').textContent='正在比较全文…';try{const result=await requestPaperAnalysis({mode:'compare',consent,papers:papers.map(p=>({id:p.id,title:p.title,pages:p.pages}))});if(result.source!=='deepseek'||!Array.isArray(result.sections))throw new Error('服务器返回无效。');const c={...result,id:uid(),paperIds:ids,titles:Object.fromEntries(papers.map(p=>[p.id,p.title]))};await commit(s=>s.comparisons.push(c));showCompare(c.id)}finally{aiBusy=false}}
  function showCompare(id){const c=state.comparisons.find(x=>x.id===id);if(!c)return;openModal(`<h2>文献比较</h2><p class="small">AI 生成 · 引文匹配原文文字；请结合原文核对结论。${c.paperIds.some(id=>!byId(id)||byId(id).fileDeleted)?'部分原文件已删除；此比较保留了当时的摘录。':''}</p><div class="paper-compare-wrap"><table class="table"><thead><tr><th>维度</th>${c.paperIds.map(id=>`<th>${e(c.titles[id])}</th>`).join('')}</tr></thead><tbody>${fields.map(f=>`<tr><th>${f}</th>${c.paperIds.map(id=>{const s=c.sections.find(x=>x.paperId===id&&x.field===f);return `<td>${e(s?.text||'未提及')}<p class="small">AI 解释：${e(s?.interpretation||'—')}</p>${(s?.evidence||[]).map(r=>`<div>${button('p.'+r.page,'compare-source',id,`data-page="${r.page}"`)}<div class="small">${e(r.quote)}</div></div>`).join('')}</td>`}).join('')}</tr>`).join('')}</tbody></table></div>${button('返回比较列表','compare-list')}`)}
  async function downloadBackup(){await queue;if(noteDrafts.size)throw new Error('还有未保存的笔记，请先重试保存再导出。');const snapshot=clone(state),zip=new JSZip(),manifest={format:'jing-papers',version:2,exportedAt:new Date().toISOString(),state:snapshot,files:[]};let n=0,total=0;
    if(snapshot.papers.length>500)throw new Error('单份备份最多 500 条文献。');
    for(const p of snapshot.papers){if(p.fileDeleted)continue;const blob=await dbRead('paper-'+p.id);if(!blob){if(p.hasLocalFile)throw new Error('原文件缺失：'+p.title+'。请重新上传后再导出完整备份。');continue}total+=blob.size;if(blob.size>MAX_FILE||total>200*1024*1024)throw new Error('原文件总计超过 200 MB 或单文件超过 40 MB，无法制作可恢复的单份备份。');const bytes=await blob.arrayBuffer(),name='files/'+(++n)+'.bin';zip.file(name,bytes);manifest.files.push({paperId:p.id,path:name,name:p.fileName||'document.pdf',type:blob.type||'application/pdf',size:blob.size,hash:await hash(bytes)})}
    const manifestText=JSON.stringify(manifest);if(new Blob([manifestText]).size>30*1024*1024)throw new Error('笔记与解析文本超过单份备份上限 30 MB。');zip.file('manifest.json',manifestText);const blob=await zip.generateAsync({type:'blob',compression:'STORE'});download(blob,'jing-papers-'+new Date().toISOString().slice(0,10)+'.zip');notice('备份已导出，包含 '+manifest.files.length+' 份原文件及笔记、标记和分析。');
  }
  function download(blob,name){const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000)}
  async function hash(bytes){return [...new Uint8Array(await crypto.subtle.digest('SHA-256',bytes))].map(x=>x.toString(16).padStart(2,'0')).join('')}
  function validateBackup(m){if(m?.format!=='jing-papers'||m.version!==2||m.state?.version!==2||!Array.isArray(m.state.papers)||m.state.papers.length>500||!Array.isArray(m.state.comparisons)||!Array.isArray(m.files))throw new Error('不是受支持的 Papers 备份。');const ids=new Set();
    for(const p of m.state.papers){if(typeof p.id!=='string'||ids.has(p.id)||typeof p.title!=='string'||typeof p.notes!=='string'||!Array.isArray(p.pages)||p.pages.length>500||!Array.isArray(p.highlights)||!Array.isArray(p.evidence)||!Array.isArray(p.analyses))throw new Error('备份的文献记录无效。');ids.add(p.id);if(!Number.isInteger(p.page)||p.page<1||!Number.isFinite(p.zoom)||p.zoom<.25||p.zoom>3)throw new Error('备份阅读位置无效。');for(const pg of p.pages)if(!Number.isInteger(pg.page)||pg.page<1||typeof pg.text!=='string')throw new Error('备份页面无效。');for(const r of [...p.highlights,...p.evidence]){if(typeof r.id!=='string'||typeof r.text!=='string'||!Array.isArray(r.rects)||r.rects.some(v=>['x','y','w','h'].some(k=>!Number.isFinite(v[k])||v[k]<0||v[k]>1)))throw new Error('备份标记无效。');if(r.page!=null&&(!Number.isInteger(r.page)||r.page<1||r.page>500))throw new Error('备份标记页码无效。')}for(const a of p.analyses)validateSections(a)}
    const files=new Set();for(const f of m.files){if(!ids.has(f.paperId)||files.has(f.paperId)||!/^files\/\d+\.bin$/.test(f.path)||!Number.isInteger(f.size)||f.size<1||f.size>MAX_FILE||!/^[a-f0-9]{64}$/.test(f.hash))throw new Error('备份文件清单无效。');files.add(f.paperId)}for(const p of m.state.papers)if(p.hasLocalFile&&!p.fileDeleted&&!files.has(p.id))throw new Error('备份缺少原文件。');for(const c of m.state.comparisons){if(!Array.isArray(c.paperIds)||c.paperIds.length>5||!c.titles||typeof c.titles!=='object')throw new Error('备份比较无效。');validateSections(c)}return m;
  }
  function validateSections(a){if(!a||typeof a.id!=='string'||!Array.isArray(a.sections)||a.sections.length>30)throw new Error('备份分析无效。');for(const s of a.sections){if(typeof s.paperId!=='string'||typeof s.field!=='string'||typeof s.text!=='string'||typeof s.interpretation!=='string'||!Array.isArray(s.evidence)||s.evidence.some(r=>!Number.isInteger(r.page)||r.page<1||typeof r.quote!=='string'))throw new Error('备份分析来源无效。')}}
  async function restore(file){try{if(file.size>250*1024*1024)throw new Error('备份超过 250 MB，请分批管理文献。');notice('正在检查备份…');const zip=await JSZip.loadAsync(file),mf=zip.file('manifest.json');if(!mf||mf._data?.uncompressedSize>30*1024*1024)throw new Error('备份清单缺失或过大。');const m=validateBackup(JSON.parse(await mf.async('text'))),puts=[],idMap=new Map(m.state.papers.map(p=>[p.id,uid()]));let total=0;
      for(const f of m.files){const entry=zip.file(f.path);total+=f.size;if(!entry||entry._data?.uncompressedSize!==f.size||total>200*1024*1024)throw new Error('备份原文件缺失或大小无效。');const bytes=await entry.async('arraybuffer');if(bytes.byteLength!==f.size||await hash(bytes)!==f.hash)throw new Error('备份文件校验失败，未导入任何记录。');puts.push(['paper-'+idMap.get(f.paperId),new File([bytes],f.name,{type:f.type})])}
      if(!confirm(`已检查 ${m.state.papers.length} 条文献和 ${puts.length} 份原文件。将作为新增副本导入，现有记录保留。继续？`)){notice('已取消导入。');return}
      const remapSections=a=>({...a,id:uid(),sections:a.sections.map(x=>({...x,paperId:idMap.get(x.paperId)||x.paperId}))});
      await commit(s=>{for(const p of m.state.papers){const q=normalize(p);q.id=idMap.get(p.id);q.analyses=p.analyses.map(remapSections);const activeIndex=p.analyses.findIndex(a=>a.id===p.activeAnalysis);q.activeAnalysis=q.analyses[activeIndex]?.id||q.analyses.at(-1)?.id||'';s.papers.push(q)}for(const c of m.state.comparisons)s.comparisons.push({...remapSections(c),paperIds:c.paperIds.map(id=>idMap.get(id)||id),titles:Object.fromEntries(Object.entries(c.titles).map(([id,t])=>[idMap.get(id)||id,t]))})},puts);notice('导入完成，原文件、笔记、标记和分析已恢复为新增副本。');
    }catch(err){notice('导入失败：'+errorText(err),true)}
  }
  async function handleAction(ev){const b=ev.target.closest('[data-paper-action]');if(!b)return;const action=b.dataset.paperAction,id=b.dataset.id,p=byId(reader);try{
    switch(action){
      case 'open':return openPaper(id);
      case 'close':closeReader();return;
      case 'metadata':metadata(id);return;
      case 'metadata-save':{const title=$('paperMeta-title').value.trim(),year=$('paperMeta-year').value.trim();if(!title)throw new Error('请填写标题。');if(year&&!/^\d{4}$/.test(year))throw new Error('年份请填写四位数字，或留空。');const authors=$('paperMeta-authors').value.trim(),course=$('paperMeta-course').value,status=$('paperMeta-status').value;await commit(s=>Object.assign(s.papers.find(x=>x.id===id),{title,authors,year,course,status}));closeModal();return;}
      case 'delete':return deletion(id);
      case 'delete-keep':return await remove(id,true);
      case 'delete-all':if(confirm('确认永久删除此文献及其笔记、证据和分析？'))await remove(id,false);return;
      case 'export':await downloadBackup();return;
      case 'import-backup':$('paperBackupFile').click();return;
      case 'original':return openStoredWorkspaceFile('paper-'+id,byId(id)?.fileName||'document.pdf');
      case 'side':side=id;editor=null;renderSide();return;
      case 'mobile':mobile=id;if(id!=='document')side=id;editor=null;renderSide();return;
      case 'page-prev':return await goPage(p.page-1);
      case 'page-next':return await goPage(p.page+1);
      case 'zoom-in':case 'zoom-out':case 'fit':{if(!pdf)return;const zoom=action==='fit'?Math.max(.25,Math.min(3,($('paperPdfScroll').clientWidth-40)/(await pdf.getPage(p.page)).getViewport({scale:1}).width)):Math.max(.25,Math.min(3,p.zoom+(action==='zoom-in'?.15:-.15)));await saveInput(p.id,'zoom',zoom);selected=null;await renderPage();return;}
      case 'annotate':case 'evidence-new':if(!selected)return;editor={kind:action==='annotate'?'highlights':'evidence',record:{...clone(selected),id:uid(),color:action==='annotate'?'yellow':'green'}};side=action==='annotate'?'notes':'evidence';if(innerWidth<=760)mobile='notes';renderSide();return;
      case 'record-cancel':editor=null;renderSide();return;
      case 'record-save':{const r={...editor.record,color:$('paperRecordColor').value,note:$('paperRecordNote').value},kind=editor.kind;if(kind==='evidence'){r.claim=$('paperRecordClaim').value;r.course=$('paperRecordCourse').value;r.assignment=$('paperRecordAssignment').value}await commit(s=>{const list=s.papers.find(x=>x.id===p.id)[kind],i=list.findIndex(x=>x.id===r.id);if(i<0)list.push(r);else list[i]=r});editor=null;selected=null;renderSide();paintMarks(r.id);saved('标记已保存');return;}
      case 'record-edit':{const kind=b.dataset.kind;editor={kind,record:clone(p[kind].find(x=>x.id===id))};renderSide();return;}
      case 'record-delete':if(confirm('删除这条记录？')){const kind=b.dataset.kind;await commit(s=>{const q=s.papers.find(x=>x.id===p.id);q[kind]=q[kind].filter(x=>x.id!==id)});renderSide();paintMarks()}return;
      case 'promote':editor={kind:'evidence',record:{...clone(p.highlights.find(x=>x.id===id)),id:uid(),color:'green'}};side='evidence';renderSide();return;
      case 'locate':{const r=[...p.highlights,...p.evidence].find(x=>x.id===id);if(!r?.page||!pdf)throw new Error('原文件或页码不可用；记录仍保留。');await goPage(r.page);mobile='document';renderSide();paintMarks(id);$('paperMarks').querySelector('.located')?.scrollIntoView({block:'center'});return;}
      case 'source':await goPage(Number(id));mobile='document';renderSide();return;
      case 'retry-notes':await saveInput(p.id,'notes',$('paperNotes').value);return;
      case 'evidence-open':await openPaper(id);side='evidence';mobile='notes';editor={kind:'evidence',record:clone(byId(id).evidence.find(x=>x.id===b.dataset.record))};renderSide();return;
      case 'assignment':{const value=b.dataset.assignment;if(!value)throw new Error('这条证据尚未关联作业。');if(!assignments().some(a=>a[0]===value))throw new Error('原作业已删除，关联记录仍然保留。');closeReader();const at=value.indexOf(':'),type=value.slice(0,at),ref=value.slice(at+1);return type==='catalog'?openAssignment(ref):type==='custom'?openCustomAssignment(ref):openGeneratedAssignment(ref);}
      case 'explain-selection':side='understand';mobile='understand';renderSide();$('paperQuestion').value='请用中文解释所选段落，保留关键英文术语，并指出它在这篇研究中的含义。';return;
      case 'connection':closeReader();return openWorkspaceConnection();
      case 'text-preview':{const pre=document.createElement('pre');pre.className='paper-record';pre.style.whiteSpace='pre-wrap';pre.textContent=p.pages.map(x=>'[p.'+x.page+']\n'+(x.text||'本页无文字')).join('\n\n');$('paperSideBody').append(pre);return;}
      case 'analyze-summary':return await analyze('summary');
      case 'analyze-question':return await analyze('question');
      case 'regenerate':{const prev=p.analyses.find(a=>a.id===id);return await analyze(prev.mode,prev);}
      case 'analysis-save':return await saveAnalysis(id);
      case 'analysis-delete':if(confirm('删除这个分析版本？')){await commit(s=>{const q=s.papers.find(x=>x.id===p.id);q.analyses=q.analyses.filter(x=>x.id!==id);q.activeAnalysis=q.analyses.at(-1)?.id||''});renderSide()}return;
      case 'compare-run':return await compare();
      case 'compare-open':return showCompare(id);
      case 'compare-list':return openPaperCompare();
      case 'compare-delete':if(confirm('删除这份比较结果？')){await commit(s=>{s.comparisons=s.comparisons.filter(x=>x.id!==id)});openPaperCompare()}return;
      case 'compare-source':if(!byId(id)||byId(id).fileDeleted)throw new Error('原文件已删除；比较中的来源摘录仍保留。');await openPaper(id);if(pdf)await goPage(Number(b.dataset.page));return;
    }
  }catch(err){const msg=errorText(err),target=$('paperRecordError')||$('paperMetaError')||$('paperDeleteError')||$('paperCompareStatus');if(target){target.textContent=msg;target.className='paper-error'}else if(reader){lastError=msg;saved(msg,true);const status=$('paperAIStatus');if(status){status.textContent=msg;status.className='paper-error'}}else notice(msg,true)}}
  document.addEventListener('click',handleAction);
  addEventListener('beforeunload',ev=>{if(pendingWrites||noteDrafts.size){ev.preventDefault();ev.returnValue=''}});
  deletePaper=id=>deletion(id);
  openLocalPaper=id=>openPaper(id);
  const priorUpdate=updatePaper;
  updatePaper=function(id,key,value){if(!ready||!byId(id))return priorUpdate(id,key,value);saveInput(id,key,value)};
  // Dashboard completion writes through its own persistence function: mirror only paper status.
  const priorComplete=completePriorityItem;
  completePriorityItem=function(id,done){priorComplete(id,done);if(String(id).startsWith('paper:')){const paperId=id.slice(6),p=workspaceState.papers.find(p=>p.id===paperId);if(p&&byId(paperId))saveInput(paperId,'status',p.status)}};
  buildLibrary();
  const initialized=(async()=>{try{const stored=await dbRead(KEY);if(stored){state=stored;state.papers=state.papers.map(normalize)}else{state.papers=workspaceState.papers.map(normalize);await write(state)}ready=true;project();renderPapers()}catch(err){notice('文献库无法打开：'+errorText(err)+'。请允许浏览器本地存储并刷新；旧数据未删除。',true)}})();
  window.Papers={ready:initialized,selectAnalysis:async id=>{try{await saveInput(reader,'activeAnalysis',id);renderSide()}catch(err){saved(errorText(err),true)}},validateBackup};
})();
